title: "Auntle" 
description: "Adventures in Developing Tech, Inspired by the Solo Mom Journey. Let's get auntle-logical 💪🦾"
logo: "/assets/img/helloworld_small.png"  # <- Update this filename when you upload your photo
github_username: "amyzhang-commits" 
theme: jekyll-theme-minimal
