title: "Auntle"
logo: "/assets/img/helloworld_small.png"  # <- Update this filename when you upload your photo
github_username: "amyzhang-commits"
theme: jekyll-theme-minimal
baseurl: "/auntle"
url: "https://amyzhang-commits.github.io"
